<films>
  <film>
    <id>${films.id}</id>
    <title>${films.title}</title>
    <year>${films.year}</year>
    <director>${films.director}</director>
    <stars>${films.stars}</stars>
    <review>${films.review}</review>
   </film>
</films>